ALTER TABLE tournaments
  ADD COLUMN IF NOT EXISTS home_away_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS home_away_stage VARCHAR(40);

ALTER TABLE tournament_matches
  ADD COLUMN IF NOT EXISTS stage_name VARCHAR(120),
  ADD COLUMN IF NOT EXISTS leg_number INT NOT NULL DEFAULT 1;

