import React from 'react'
import {
  Trophy,
  Gamepad2,
  Tv,
  Users,
  User,
  Calendar,
  DollarSign,
  Coins,
  Activity,
  Settings,
  AlertTriangle,
  CheckCircle2,
  Shield,
  Flame,
  Clock,
  Sparkles,
  Plus,
  Trash2,
  Edit3,
  Save,
  RefreshCw,
  Download,
  Search,
  LogOut,
  Building2,
  Receipt,
  Palette,
  Layers,
  Globe2,
  Play,
  Pause,
  Lock,
  Check,
  ChevronLeft,
  ChevronRight,
  CircleDot,
  Zap,
  BarChart3,
  ArrowRightLeft,
  Timer,
  Award,
  Radio,
  Sliders,
  CheckCheck,
  AlertCircle,
  HelpCircle,
  TrendingUp,
} from 'lucide-react'

const ICON_MAP = {
  trophy: Trophy,
  gamepad: Gamepad2,
  tv: Tv,
  display: Tv,
  users: Users,
  user: User,
  calendar: Calendar,
  schedule: Calendar,
  money: DollarSign,
  dollar: DollarSign,
  coins: Coins,
  activity: Activity,
  live: Radio,
  radio: Radio,
  settings: Settings,
  alert: AlertTriangle,
  warning: AlertTriangle,
  check: CheckCircle2,
  success: CheckCircle2,
  shield: Shield,
  flame: Flame,
  clock: Clock,
  timer: Timer,
  sparkles: Sparkles,
  plus: Plus,
  trash: Trash2,
  edit: Edit3,
  save: Save,
  refresh: RefreshCw,
  download: Download,
  search: Search,
  logout: LogOut,
  building: Building2,
  business: Building2,
  receipt: Receipt,
  subscription: Receipt,
  palette: Palette,
  branding: Palette,
  layers: Layers,
  globe: Globe2,
  play: Play,
  pause: Pause,
  lock: Lock,
  tick: Check,
  left: ChevronLeft,
  right: ChevronRight,
  ball: CircleDot,
  soccer: CircleDot,
  zap: Zap,
  barchart: BarChart3,
  chart: BarChart3,
  analytics: BarChart3,
  exchange: ArrowRightLeft,
  legs: ArrowRightLeft,
  award: Award,
  sliders: Sliders,
  verified: CheckCheck,
  error: AlertCircle,
  help: HelpCircle,
  trending: TrendingUp,
}

/**
 * Modern SVG / Lucide Icon renderer. Replaces all legacy raw emoji icons.
 */
export default function AppIcon({
  name,
  size = 18,
  className = '',
  color,
  strokeWidth = 2,
}) {
  const normalized = String(name || '').trim().toLowerCase()
  const IconComponent = ICON_MAP[normalized] || Trophy

  return (
    <IconComponent
      size={size}
      strokeWidth={strokeWidth}
      className={`inline-block shrink-0 ${className}`}
      style={color ? { color } : undefined}
    />
  )
}
