import {
  Trophy,
  Gamepad2,
  Calendar,
  Layers,
  Users,
  DollarSign,
  Tv,
  Settings,
  Flame,
  Globe,
  Sliders,
  Sparkles,
  Shield,
  Play,
  Pause,
  RotateCcw,
  Plus,
  Trash2,
  Edit,
  Check,
  Building2,
  Receipt,
  User,
  Clock,
  ArrowRight,
  Maximize2,
  Minimize2,
  Upload,
  Download,
  AlertCircle,
  BarChart3,
  TrendingUp,
  Palette,
  ArrowLeftRight,
} from 'lucide-react'

const ICON_MAP = {
  trophy: Trophy,
  gamepad: Gamepad2,
  calendar: Calendar,
  layers: Layers,
  users: Users,
  dollar: DollarSign,
  tv: Tv,
  settings: Settings,
  live: Flame,
  globe: Globe,
  sliders: Sliders,
  sparkles: Sparkles,
  shield: Shield,
  play: Play,
  pause: Pause,
  refresh: RotateCcw,
  plus: Plus,
  trash: Trash2,
  edit: Edit,
  check: Check,
  building: Building2,
  receipt: Receipt,
  user: User,
  timer: Clock,
  arrow: ArrowRight,
  expand: Maximize2,
  contract: Minimize2,
  upload: Upload,
  download: Download,
  alert: AlertCircle,
  chart: BarChart3,
  trend: TrendingUp,
  palette: Palette,
  exchange: ArrowLeftRight,
  soccer: Trophy,
}

export default function AppIcon({ name, size = 18, className = '', ...props }) {
  const IconComponent = ICON_MAP[name] || Trophy
  return <IconComponent size={size} className={className} {...props} />
}
